# base
id: vatt
caption_model: vatt
start_from: log
input_json: D:/dataset/coco_data_vgg/cocotalk.json
input_label_h5: D:/dataset/coco_data_vgg/cocotalk_label.h5
input_fc_dir: D:/dataset/coco_data_vgg/cocotalk_fc_14x14
input_att_dir: D:/dataset/coco_data_vgg/cocotalk_att_14x14

learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0
checkpoint_path: log

language_eval: 1
save_checkpoint_every: 3000
val_images_use: 5000

batch_size: 10
max_epochs: 20